# Cryptocurrency Market Data Analysis

##### Project: Crypto Market Report

In this project I will be sorting fictious data of a cryptocurrency market using Pandas, Matplotlib and Seaborn. Hope you enjoy.

In [44]:
import pandas as pd

In [45]:
import matplotlib

In [46]:
from matplotlib import pyplot as plt

In [47]:
import seaborn as sns

# Reading The .CSV File of Crypto data

In [48]:
# Let's start importing the .csv file and create
# our dataset named crypto_info
crypto_info = pd.read_csv("consolidated_coin_data.csv")
crypto_info

,Currency,Date,Open,High,Low,Close,Volume,Market Cap
0,tezos,"Dec 04, 2019",1.29,1.32,1.25,1.25,"46,048,752","824,588,509"
1,tezos,"Dec 03, 2019",1.24,1.32,1.21,1.29,"41,462,224","853,213,342"
2,tezos,"Dec 02, 2019",1.25,1.26,1.20,1.24,"27,574,097","817,872,179"
3,tezos,"Dec 01, 2019",1.33,1.34,1.25,1.25,"24,127,567","828,296,390"
4,tezos,"Nov 30, 2019",1.31,1.37,1.31,1.33,"28,706,667","879,181,680"
...,...,...,...,...,...,...,...,...
28939,bitcoin-sv,"May 02, 2013",3.78,4.04,3.01,3.37,0,"58,287,979"
28940,bitcoin-sv,"May 01, 2013",4.29,4.36,3.52,3.80,0,"65,604,596"
28941,bitcoin-sv,"Apr 30, 2013",4.40,4.57,4.17,4.30,0,"74,020,918"
28942,bitcoin-sv,"Apr 29, 2013",4.37,4.57,4.23,4.38,0,"75,388,964"
28943,bitcoin-sv,"Apr 28, 2013",4.30,4.40,4.18,4.35,0,"74,636,938"

In [49]:
# Reading only the first 25 crypto currencies on the .csv
crypto_info.head(25)

   Currency          Date  Open  High   Low Close       Volume   Market Cap
0     tezos  Dec 04, 2019  1.29  1.32  1.25  1.25   46,048,752  824,588,509
1     tezos  Dec 03, 2019  1.24  1.32  1.21  1.29   41,462,224  853,213,342
2     tezos  Dec 02, 2019  1.25  1.26  1.20  1.24   27,574,097  817,872,179
3     tezos  Dec 01, 2019  1.33  1.34  1.25  1.25   24,127,567  828,296,390
4     tezos  Nov 30, 2019  1.31  1.37  1.31  1.33   28,706,667  879,181,680
5     tezos  Nov 29, 2019  1.28  1.34  1.28  1.31   32,270,224  867,085,098
6     tezos  Nov 28, 2019  1.26  1.35  1.22  1.28   44,240,281  845,073,679
7     tezos  Nov 27, 2019  1.24  1.27  1.16  1.26   47,723,271  829,672,736
8     tezos  Nov 26, 2019  1.24  1.28  1.23  1.24   54,828,808  822,065,277
9     tezos  Nov 25, 2019  1.33  1.33  1.21  1.24   64,954,006  815,688,075
10    tezos  Nov 24, 2019  1.40  1.42  1.31  1.34   49,206,070  887,731,654
11    tezos  Nov 23, 2019  1.22  1.42  1.22  1.39  123,832,790  920,735,790
12    tezos  Nov 22, 2019  1.21  1.28  1.08  1.22   69,312,275  804,427,044
13    tezos  Nov 21, 2019  1.21  1.29  1.18  1.21   53,020,027  800,257,863
14    tezos  Nov 20, 2019  1.22  1.25  1.17  1.21   33,605,071  801,174,969
15    tezos  Nov 19, 2019  1.23  1.25  1.15  1.22   35,796,763  805,231,584
16    tezos  Nov 18, 2019  1.16  1.26  1.16  1.23   37,602,915  813,744,878
17    tezos  Nov 17, 2019  1.16  1.18  1.15  1.16   22,483,167  767,707,353
18    tezos  Nov 16, 2019  1.17  1.18  1.16  1.16   26,689,028  768,303,560
19    tezos  Nov 15, 2019  1.22  1.26  1.15  1.17   32,203,363  773,992,543
20    tezos  Nov 14, 2019  1.13  1.30  1.11  1.22   41,978,349  808,582,829
21    tezos  Nov 13, 2019  1.17  1.17  1.12  1.13   23,410,839  746,750,215
22    tezos  Nov 12, 2019  1.18  1.20  1.15  1.17   23,591,140  771,905,281
23    tezos  Nov 11, 2019  1.23  1.24  1.17  1.18   25,012,739  776,358,941
24    tezos  Nov 10, 2019  1.25  1.25  1.19  1.23   31,134,799  812,505,004

In [50]:
# Reading only the last 50 crypto currencies on the .csv
crypto_info.tail(30)

         Currency          Date  Open  High   Low Close Volume  Market Cap
28914  bitcoin-sv  May 27, 2013  3.23  3.26  3.02  3.10      0  55,882,132
28915  bitcoin-sv  May 26, 2013  3.12  3.33  3.09  3.25      0  58,457,958
28916  bitcoin-sv  May 25, 2013  3.19  3.20  3.05  3.12      0  56,026,343
28917  bitcoin-sv  May 24, 2013  3.17  3.19  3.04  3.18      0  57,017,469
28918  bitcoin-sv  May 23, 2013  3.12  3.19  3.09  3.18      0  56,949,220
28919  bitcoin-sv  May 22, 2013  3.09  3.14  3.03  3.12      0  55,766,901
28920  bitcoin-sv  May 21, 2013  3.19  3.22  3.04  3.09      0  55,073,034
28921  bitcoin-sv  May 20, 2013  3.31  3.32  3.15  3.18      0  56,682,749
28922  bitcoin-sv  May 19, 2013  3.30  3.41  3.19  3.30      0  58,760,676
28923  bitcoin-sv  May 18, 2013  3.20  3.36  3.13  3.29      0  58,518,794
28924  bitcoin-sv  May 17, 2013  2.89  3.34  2.87  3.19      0  56,498,074
28925  bitcoin-sv  May 16, 2013  2.93  2.97  2.69  2.92      0  51,685,880
28926  bitcoin-sv  May 15, 2013  2.82  3.04  2.64  2.94      0  51,891,652
28927  bitcoin-sv  May 14, 2013  3.28  3.33  2.78  2.82      0  49,847,568
28928  bitcoin-sv  May 13, 2013  3.26  3.37  3.20  3.28      0  57,790,879
28929  bitcoin-sv  May 12, 2013  3.36  3.42  3.22  3.27      0  57,513,320
28930  bitcoin-sv  May 11, 2013  3.46  3.48  3.30  3.35      0  58,809,513
28931  bitcoin-sv  May 10, 2013  3.41  3.63  3.37  3.44      0  60,358,927
28932  bitcoin-sv  May 09, 2013  3.40  3.44  3.29  3.42      0  59,755,569
28933  bitcoin-sv  May 08, 2013  3.28  3.49  3.28  3.41      0  59,508,216
28934  bitcoin-sv  May 07, 2013  3.37  3.41  2.94  3.33      0  58,051,265
28935  bitcoin-sv  May 06, 2013  3.59  3.78  3.12  3.37      0  58,594,361
28936  bitcoin-sv  May 05, 2013  3.49  3.69  3.35  3.59      0  62,298,185
28937  bitcoin-sv  May 04, 2013  3.03  3.64  2.90  3.48      0  60,290,868
28938  bitcoin-sv  May 03, 2013  3.39  3.45  2.40  3.04      0  52,694,847
28939  bitcoin-sv  May 02, 2013  3.78  4.04  3.01  3.37      0  58,287,979
28940  bitcoin-sv  May 01, 2013  4.29  4.36  3.52  3.80      0  65,604,596
28941  bitcoin-sv  Apr 30, 2013  4.40  4.57  4.17  4.30      0  74,020,918
28942  bitcoin-sv  Apr 29, 2013  4.37  4.57  4.23  4.38      0  75,388,964
28943  bitcoin-sv  Apr 28, 2013  4.30  4.40  4.18  4.35      0  74,636,938

In [51]:
# Sorting data by Currency name
crypto_info.sort_values('Currency')

,Currency,Date,Open,High,Low,Close,Volume,Market Cap
3617,binance-coin,"Aug 16, 2016",3.59,3.65,3.58,3.64,"2,302,180","171,483,591"
3217,binance-coin,"Sep 20, 2017",0.815032,0.816384,0.743676,0.747890,"2,536,950","74,789,000"
3216,binance-coin,"Sep 21, 2017",0.764013,0.781775,0.684281,0.702140,"2,238,040","70,214,000"
3215,binance-coin,"Sep 22, 2017",0.698871,0.740154,0.683260,0.715893,"2,099,500","71,589,300"
3214,binance-coin,"Sep 23, 2017",0.717196,0.777400,0.707845,0.770965,"2,276,080","77,096,500"
...,...,...,...,...,...,...,...,...
12865,xrp,"Sep 20, 2017",0.183710,0.186229,0.180333,0.182078,"34,521,600","6,981,570,042"
12866,xrp,"Sep 19, 2017",0.189819,0.190680,0.181334,0.184041,"54,046,100","7,056,839,004"
12867,xrp,"Sep 18, 2017",0.178309,0.190019,0.178309,0.189768,"88,397,904","7,276,434,186"
12869,xrp,"Sep 16, 2017",0.181925,0.187417,0.172279,0.179082,"84,495,200","6,866,691,892"
14471,xrp,"Apr 28, 2013",135.30,135.98,132.10,134.21,0,"1,488,566,728"